### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by InSyncWithFoo** [erictraut/pyright-playground#10]
It seems to have been down for the last few days. Could you have a look?

**Comment by erictraut** [comment]
It looks like there's some problem with 1.1.364 on the playground server. If you switch to an older version of pyright, it works fine. I'll investigate.

**Comment by erictraut** [comment]
Looks like something was corrupted on the playground server. I've fixed the issue, and it appears to be working fine again.

Thanks for reporting the issue.
