### ISSUE TITLE
Include typing-extensions and other popular modules

### ISSUE THREAD

**Issue by Andrej730** [erictraut/pyright-playground#11]
I think `typing_extensions` must be available to support copying/pasting code snippets from older Python versions without tweaking them each time not to use `typing_extensions`. It especially makes sense as playground does allow using older Python versions.

![image](https://github.com/erictraut/pyright-playground/assets/9417531/86e44a4b-6ca8-4ebc-bf9e-a5d31cb91a9a)

Perhaps, there is also some need to include some other popular modules? Personally, I would be using playground for testing `numpy` stuff too but not sure if there is enough demand for this from the community.

**Comment by erictraut** [comment]
Pyright playground represents a "bare" install of pyright with no Pyright environment and no third-party libraries. It contains only the stubs that are bundled with pyright. It would go against the design and intent to install third-party libraries. If you want to use pyright with additional libraries, install it locally on your development machine.
