### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by Viicos** [erictraut/pyright-playground#13]
Seems like any POST call to `https://pyright-playground.azurewebsites.net/api/session` ends up timing out since last week, at least on my end.

**Comment by erictraut** [comment]
Thanks for the heads up. Looks like the server ran out of storage. I deleted a bunch of older pyright versions (which it caches), and this appears to have fixed the problem. Let me know if you continue to see issues.

**Comment by Viicos** [comment]
Thanks for the quick follow up, it works now.
