### ISSUE TITLE
Missing signature help with callables having a keyword only specifier

### ISSUE THREAD

**Issue by Viicos** [erictraut/pyright-playground#14]
Code sample in [pyright playground](https://pyright-play.net/?pythonVersion=3.12&strict=true&locale=en-us&enableExperimentalFeatures=true&code=CYUwZgBALiDOUAoBUAaCBDAXBAlgOygEpsAHdWWAKEpngUMqA)

```python
def test(*, a: int): pass

test()
```

![image](https://github.com/user-attachments/assets/04f7d623-861c-44d8-8a8a-4fd2c6bbbf82)

For some reason, the `signature` endpoint does not provide a value for the [`activeSignature`](https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.SignatureHelp.html#activeSignature) property. Manually intercepting the request and adding `activeSignature: 0` works as expected. I'll note that it works on VSCode w/ Pylance.

**Comment by erictraut** [comment]
Thanks for the bug report. This is now fixed.
